# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Run Tests and Build Backend Services
          command: |
            pushd services
            mvn clean package
      - run:
          name: Save Tests
          command: |
            mkdir -p ~/junit
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            ls -ltr ~/junit
      - store_test_results:
          path: ~/junit
  build_ui:
    docker:
      - image: circleci/node:10-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            pushd ui
            npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
              - ui/node_modules
      - run:
          name: Run Tests
          command: |
            pushd ui
            npm run test
      - run:
          name: Save-Tests
          command: |
            mkdir -p ~/junit
            find . -type f -regex ".*/test/junit/.*xml" -exec cp {} ~/junit/ \;
      - run:
          name: Build Application
          command: |
            pushd ui
            npm run build
      - store_test_results:
          path: ~/junit
workflows:
  version: 2
  build_services_and_ui:
    jobs:
      - build
      - build_ui
