# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Run-Tests-And-Build-Backend-Services
          command: |
            pushd services
            mvn clean package
      - run:
          name: Save-Tests
          command: |
            mkdir -p ~/junit
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            ls -ltr ~/junit
      - store_test_results:
          path: ~/junit
  build_ui:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run-Tests-And-Build-UI
          command: |
            pushd ui
            npm run test
            npm run build
      - run:
          name: Save-Tests
          command: |
            mkdir -p ~/junit
            find . -type f -regex ".*/test/junit/.*xml" -exec cp {} ~/junit/ \;
      - store_test_results:
          path: ~/junit
workflows:
  version: 2
  build_services_and_ui:
    jobs:
      - build
      - build_ui
